/**
 * Organized Quote Database Seeding System
 * Allows easy addition of new quotes without losing existing data
 */

export interface QuoteData {
  text: string;
  author: string;
  category: 'Love' | 'Science' | 'History' | 'Finance';
}

export const historyQuotes: QuoteData[] = [
  { text: "History is written by the victors.", author: "Winston Churchill", category: "History" },
  { text: "Those who cannot remember the past are condemned to repeat it.", author: "George Santayana", category: "History" },
  { text: "Study the past if you would define the future.", author: "Confucius", category: "History" },
  { text: "History doesn't repeat itself, but it often rhymes.", author: "(Attributed to) Mark Twain", category: "History" },
  { text: "People are trapped in history and history is trapped in them.", author: "James Baldwin", category: "History" },
  { text: "We are not makers of history. We are made by history.", author: "Martin Luther King Jr.", category: "History" },
  { text: "History is a vast early-warning system.", author: "Norman Cousins", category: "History" },
  { text: "The more you know about the past, the better prepared you are for the future.", author: "Theodore Roosevelt", category: "History" },
  { text: "History is who we are and why we are the way we are.", author: "David McCullough", category: "History" },
  { text: "History will be kind to me, for I intend to write it.", author: "Winston Churchill", category: "History" },
  { text: "History is philosophy teaching by examples.", author: "Thucydides", category: "History" },
  { text: "The past is never dead. It's not even past.", author: "William Faulkner", category: "History" },
  { text: "History is a set of lies agreed upon.", author: "Napoleon Bonaparte", category: "History" },
  { text: "What experience and history teach is that people and governments have never learned anything from history.", author: "G. W. F. Hegel", category: "History" },
  { text: "The past is a foreign country; they do things differently there.", author: "L. P. Hartley", category: "History" },
  { text: "The historian's first duty is to be on guard against his own predilections.", author: "Edward Gibbon", category: "History" },
  { text: "History teaches everything, including the future.", author: "Alphonse de Lamartine", category: "History" },
  { text: "History is a gallery of pictures in which there are few originals and many copies.", author: "Alexis de Tocqueville", category: "History" },
  { text: "History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.", author: "Maya Angelou", category: "History" },
  { text: "History is a race between education and catastrophe.", author: "H. G. Wells", category: "History" },
  { text: "The lessons of history are that nothing is ever simple.", author: "Margaret MacMillan", category: "History" },
  { text: "History smiles at all attempts to force its currents into artificial channels.", author: "Will Durant", category: "History" },
  { text: "History repeats itself, first as tragedy, second as farce.", author: "Karl Marx", category: "History" },
  { text: "A generation which ignores history has no past and no future.", author: "Robert A. Heinlein", category: "History" },
  { text: "History is written with blood and tears.", author: "Unknown", category: "History" },
  { text: "History does not long entrust the care of freedom to the weak or the timid.", author: "Dwight D. Eisenhower", category: "History" },
  { text: "History is the witness that testifies to the passing of time.", author: "Cicero", category: "History" },
  { text: "History never looks like history when you are living through it.", author: "John W. Gardner", category: "History" },
  { text: "If you want to understand today, you have to search yesterday.", author: "Pearl S. Buck", category: "History" },
  { text: "The very ink with which history is written is merely fluid prejudice.", author: "(Attributed to) Mark Twain", category: "History" },
  { text: "History is the sum total of things that could have been avoided.", author: "Konrad Adenauer", category: "History" },
  { text: "History is a relentless master.", author: "John F. Kennedy", category: "History" },
  { text: "History is more or less bunk.", author: "Henry Ford", category: "History" },
  { text: "History is not was, it is.", author: "William Faulkner", category: "History" },
  { text: "History is a pattern of timeless moments.", author: "T. S. Eliot", category: "History" },
  { text: "History punishes those who come too late.", author: "Mikhail Gorbachev", category: "History" },
  { text: "The duty of every historian is to make the past intelligible.", author: "Ernst Nolte", category: "History" },
  { text: "History is a cyclic poem written by time upon the memories of man.", author: "Percy Bysshe Shelley", category: "History" },
  { text: "History is the best antidote to the illusions of omnipotence.", author: "Henry Kissinger", category: "History" },
  { text: "History is the memory of states.", author: "Henry Kissinger", category: "History" },
  { text: "History is the essence of innumerable biographies.", author: "Thomas Carlyle", category: "History" },
  { text: "History teaches us that men and nations behave wisely once they have exhausted all other alternatives.", author: "Abba Eban", category: "History" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt", category: "History" },
  { text: "The historian's task is not to judge but to understand.", author: "Fernand Braudel", category: "History" },
  { text: "History offers no refuge from the present.", author: "Benjamin Disraeli", category: "History" },
  { text: "History is the ship carrying living memories to the future.", author: "Stephen Ambrose", category: "History" },
  { text: "History is the mother of truth.", author: "Miguel de Cervantes", category: "History" },
  { text: "History's lessons are never easy.", author: "Condoleezza Rice", category: "History" },
  { text: "History has to be rewritten because history changes.", author: "Gertrude Stein", category: "History" },
  { text: "The great thing about history is that it is always changing.", author: "James H. Billington", category: "History" },
  { text: "History is a grand instructor.", author: "Edmund Burke", category: "History" },
  { text: "History is the only laboratory we have in which to test the consequences of thought.", author: "Étienne Gilson", category: "History" },
  { text: "History is a vast storehouse of knowledge.", author: "Thucydides", category: "History" },
  { text: "History is the torch that illuminates the past to guard us against the future.", author: "Edward Bolton", category: "History" },
  { text: "History is a guide to navigation in perilous times.", author: "David McCullough", category: "History" },
  { text: "History offers a view of our journey and reminds us of our steps.", author: "Unknown", category: "History" },
  { text: "History warns that it is the customary fate of new truths to begin as heresies.", author: "Thomas Huxley", category: "History" },
  { text: "A small body of determined spirits can alter the course of history.", author: "Mahatma Gandhi", category: "History" },
  { text: "History delights in riddles.", author: "Will Durant", category: "History" },
  { text: "History is a symphony of echoes heard and unheard.", author: "Charles Angoff", category: "History" },
  { text: "History belongs to the intercessors.", author: "Walter Brueggemann", category: "History" },
  { text: "History feeds the roots of the present.", author: "Unknown", category: "History" },
  { text: "History is the storyline of humanity.", author: "Unknown", category: "History" },
  { text: "History demands to be heard.", author: "Unknown", category: "History" },
  { text: "History is bound to repeat itself until it is faced.", author: "Unknown", category: "History" },
  { text: "History ends up in the dustbin if it fails to educate.", author: "Unknown", category: "History" },
  { text: "History is the master key to human affairs.", author: "Unknown", category: "History" },
  { text: "History shapes the hand of time.", author: "Unknown", category: "History" },
  { text: "History is a record of humanity's long learning process.", author: "John Hope Franklin", category: "History" },
  { text: "History is made by the deeds of determined people.", author: "John Keegan", category: "History" },
  { text: "History is a construction; step back and see the builder.", author: "Unknown", category: "History" },
  { text: "History is the great adviser.", author: "Unknown", category: "History" },
  { text: "History offers no blank pages.", author: "Unknown", category: "History" },
  { text: "History is the polemic of the victor.", author: "William F. Buckley Jr.", category: "History" },
  { text: "History is a mirror in which we see the future.", author: "Unknown", category: "History" },
  { text: "History remembers only the sensational.", author: "John Gunther", category: "History" },
  { text: "History is written in revolt, rebellion, and ruin.", author: "Unknown", category: "History" },
  { text: "History speaks to artists; it reshapes their vision.", author: "Anselm Kiefer", category: "History" },
  { text: "History is the product of innumerable acts of violence.", author: "R. J. Rummel", category: "History" },
  { text: "History is the unfolding of miscalculations.", author: "Barbara Tuchman", category: "History" },
  { text: "History is the collective memory of mankind.", author: "Unknown", category: "History" },
  { text: "History is the best guide to the future, but seldom followed.", author: "Unknown", category: "History" },
  { text: "History is not only a record, it is a responsibility.", author: "Unknown", category: "History" },
  { text: "History never forgives those who forget.", author: "Unknown", category: "History" },
  { text: "Each of us has a part to play in the story of history.", author: "Nelson Mandela", category: "History" },
  { text: "History is a relentless debate between past and present.", author: "Peter Gay", category: "History" },
  { text: "History must stay open; it is always in the making.", author: "Otto Frank", category: "History" },
  { text: "The history of liberty is the history of resistance.", author: "Woodrow Wilson", category: "History" },
  { text: "History is the best teacher with the worst pupils.", author: "Indira Gandhi", category: "History" },
  { text: "History is the great drama with man as both actor and historian.", author: "José Ortega y Gasset", category: "History" },
  { text: "History is a contest of narratives.", author: "Yuval Noah Harari", category: "History" },
  { text: "History's shadows define our present.", author: "Unknown", category: "History" },
  { text: "History offers perspective; without it we are blind.", author: "Unknown", category: "History" },
  { text: "History is a torch lighting our way.", author: "Unknown", category: "History" },
  { text: "History rewards the curious.", author: "Unknown", category: "History" },
  { text: "History is the mother of understanding.", author: "Unknown", category: "History" },
  { text: "History is the fruit of hindsight.", author: "Unknown", category: "History" },
  { text: "History is a conversation between the present and the past.", author: "Unknown", category: "History" },
  { text: "History is the foundation of identity.", author: "Unknown", category: "History" },
  { text: "History lives in every moment we create.", author: "Unknown", category: "History" }
];

export const scienceQuotes: QuoteData[] = [
  { text: "The scientist is not a person who gives the right answers, but the one who asks the right questions.", author: "Claude Lévi-Strauss", category: "Science" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existence.", author: "Albert Einstein", category: "Science" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan", category: "Science" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan", category: "Science" },
  { text: "Equipped with his five senses, man explores the universe around him and calls the adventure Science.", author: "Edwin Hubble", category: "Science" },
  { text: "Science knows no country, because knowledge belongs to humanity.", author: "Louis Pasteur", category: "Science" },
  { text: "In science the credit goes to the man who convinces the world, not to whom the idea first occurs.", author: "Francis Darwin", category: "Science" },
  { text: "Science is organized knowledge.", author: "Herbert Spencer", category: "Science" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson", category: "Science" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", author: "Isaac Newton", category: "Science" },
  { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", category: "Science" },
  { text: "Research is what I'm doing when I don't know what I'm doing.", author: "Wernher von Braun", category: "Science" },
  { text: "Science is the great antidote to the poison of superstition.", author: "Adam Smith", category: "Science" },
  { text: "Science is the acceptance of what works and the rejection of what does not.", author: "Jacob Bronowski", category: "Science" },
  { text: "Science and everyday life cannot and should not be separated.", author: "Rosalind Franklin", category: "Science" },
  { text: "It is far better to grasp the universe as it really is than to persist in delusion.", author: "Carl Sagan", category: "Science" },
  { text: "The most exciting phrase in science is not 'Eureka!' but 'That's funny…'", author: "Isaac Asimov", category: "Science" },
  { text: "Science is the engine of prosperity.", author: "George Osborne", category: "Science" },
  { text: "Science is the knowledge of consequences.", author: "Thomas Hobbes", category: "Science" },
  { text: "Science is the great adventure of our age.", author: "Freeman Dyson", category: "Science" },
  { text: "Science is wonderfully equipped to answer the question 'How?' but gets confused with 'Why?'", author: "Erwin Chargaff", category: "Science" },
  { text: "Every brilliant experiment begins with an act of imagination.", author: "Jonah Lehrer", category: "Science" },
  { text: "Science is magic that works.", author: "Kurt Vonnegut", category: "Science" },
  { text: "We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.", author: "Carl Sagan", category: "Science" },
  { text: "Science is a differential equation. Religion is a boundary condition.", author: "Alan Turing", category: "Science" },
  { text: "The whole of science is nothing more than a refinement of everyday thinking.", author: "Albert Einstein", category: "Science" },
  { text: "Science is a beautiful gift to humanity; we should not distort it.", author: "A. P. J. Abdul Kalam", category: "Science" },
  { text: "Science is the systematic classification of experience.", author: "George Henry Lewes", category: "Science" },
  { text: "The science of today is the technology of tomorrow.", author: "Edward Teller", category: "Science" },
  { text: "Science is the poetry of reality.", author: "Richard Dawkins", category: "Science" },
  { text: "Science is simply common sense at its best.", author: "Thomas Huxley", category: "Science" },
  { text: "Science without religion is lame; religion without science is blind.", author: "Albert Einstein", category: "Science" },
  { text: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson", category: "Science" },
  { text: "Science flies you to the moon; religion flies you into buildings.", author: "Victor Stenger", category: "Science" },
  { text: "Wonder is the seed of knowledge.", author: "Francis Bacon", category: "Science" },
  { text: "Science progresses one funeral at a time.", author: "Max Planck", category: "Science" },
  { text: "Science is the key to our future, and if you don't believe in science, you're holding everybody back.", author: "Bill Nye", category: "Science" },
  { text: "Science is facts; just as houses are made of stones, so is science made of facts.", author: "Henri Poincaré", category: "Science" },
  { text: "Art and science have their meeting point in method.", author: "Edward G. Bulwer-Lytton", category: "Science" },
  { text: "Science is not only a disciple of reason but also one of romance and passion.", author: "Stephen Hawking", category: "Science" },
  { text: "Science is the belief in the ignorance of experts.", author: "Richard Feynman", category: "Science" },
  { text: "For every fact there is an infinity of hypotheses.", author: "Robert M. Pirsig", category: "Science" },
  { text: "Science is a rebellion against ignorance.", author: "Unknown", category: "Science" },
  { text: "Science is fun. Science is curiosity.", author: "Sally Ride", category: "Science" },
  { text: "Science is the one culture.", author: "Jacob Bronowski", category: "Science" },
  { text: "Science and technology revolutionize our lives, but memory, tradition, and myth frame our response.", author: "Arthur M. Schlesinger Jr.", category: "Science" },
  { text: "Truth in science is the working hypothesis best suited to open the way to the next better one.", author: "Konrad Lorenz", category: "Science" },
  { text: "Science is what we understand well enough to explain to a computer.", author: "Donald Knuth", category: "Science" },
  { text: "Science is a way to try not to fool yourself.", author: "Richard Feynman", category: "Science" },
  { text: "Science is organized curiosity.", author: "Unknown", category: "Science" },
  { text: "Science is prediction.", author: "Freeman Dyson", category: "Science" },
  { text: "Science is the language of nature.", author: "Galileo Galilei", category: "Science" },
  { text: "Science becomes dangerous only when it imagines it has achieved its goal.", author: "George Bernard Shaw", category: "Science" },
  { text: "Science is what you know; philosophy is what you don't know.", author: "Bertrand Russell", category: "Science" },
  { text: "Science investigates; religion interprets.", author: "Martin Luther King Jr.", category: "Science" },
  { text: "Science commits suicide when it adopts a creed.", author: "Thomas Huxley", category: "Science" },
  { text: "Science is organized skepticism.", author: "Michael Shermer", category: "Science" },
  { text: "Science is the best idea humans have ever had.", author: "Bill Nye", category: "Science" },
  { text: "Science does not know its debt to imagination.", author: "Ralph Waldo Emerson", category: "Science" },
  { text: "Science is the great engine of change.", author: "James Burke", category: "Science" },
  { text: "Science is a candle in the dark.", author: "Carl Sagan", category: "Science" },
  { text: "Science adjusts its views based on what's observed.", author: "Tim Minchin", category: "Science" },
  { text: "Science is the process that takes us from confusion to understanding.", author: "Brian Greene", category: "Science" },
  { text: "Science is the key to unlocking humanity's potential.", author: "Unknown", category: "Science" },
  { text: "Science is nothing but perception.", author: "Plato", category: "Science" },
  { text: "Science is continuous proof—all the time.", author: "Shakuntala Devi", category: "Science" },
  { text: "Science is the progressive disclosure of God.", author: "Frank Lloyd Wright", category: "Science" },
  { text: "Science is imagination in the service of the verifiable.", author: "Unknown", category: "Science" },
  { text: "Science is built up with facts, as a house is with stones.", author: "Jules Henri Poincaré", category: "Science" },
  { text: "Science is an attempt to understand the universe.", author: "Richard Dawkins", category: "Science" },
  { text: "Science is the conscience of modern society.", author: "Unknown", category: "Science" },
  { text: "Science gives man what he needs; culture gives man what he wants.", author: "Unknown", category: "Science" },
  { text: "Science never solves a problem without creating ten more.", author: "George Bernard Shaw", category: "Science" },
  { text: "Science is a mosaic of culture.", author: "Carl Sagan", category: "Science" },
  { text: "Science is respect for the facts.", author: "Unknown", category: "Science" },
  { text: "Science is a great game—refreshing and inspiring.", author: "I. I. Rabi", category: "Science" },
  { text: "Science is the mother of knowledge.", author: "Unknown", category: "Science" },
  { text: "Science is more than a body of knowledge; it's a way of thinking.", author: "Carl Sagan", category: "Science" },
  { text: "Science is the acceptance of evidence.", author: "Unknown", category: "Science" },
  { text: "Science cannot solve the ultimate mystery of nature.", author: "Max Planck", category: "Science" },
  { text: "Science is what we do to keep from lying to ourselves.", author: "Richard Feynman", category: "Science" },
  { text: "Science is a careful discipline that demands evidence.", author: "Brian Greene", category: "Science" },
  { text: "Science walks forward on two feet, namely theory and experiment.", author: "Robert A. Millikan", category: "Science" },
  { text: "Science without conscience is the soul's perdition.", author: "François Rabelais", category: "Science" },
  { text: "Science is curiosity put into action.", author: "Unknown", category: "Science" },
  { text: "The great tragedy of science is the slaying of a beautiful hypothesis by an ugly fact.", author: "Thomas Huxley", category: "Science" },
  { text: "Science is organized common sense where many a beautiful theory was killed by an ugly fact.", author: "Thomas Huxley", category: "Science" },
  { text: "Science is the great road out of darkness.", author: "Louis Pasteur", category: "Science" },
  { text: "Science is the father of knowledge.", author: "Hippocrates", category: "Science" },
  { text: "Science is a differential equation; religion a boundary condition.", author: "Alan Turing", category: "Science" },
  { text: "Science is the progressive discovery of ignorance.", author: "Will Durant", category: "Science" },
  { text: "Science is knowledge which we understand so well that we can teach it to a computer.", author: "Edward Feigenbaum", category: "Science" },
  { text: "Science means simply the aggregate of all the recipes that are always successful.", author: "Henri Poincaré", category: "Science" },
  { text: "Science is the search for truth.", author: "Linus Pauling", category: "Science" },
  { text: "Science is a way of life that uses skepticism and evidence.", author: "Unknown", category: "Science" },
  { text: "Science is the bridge between bewilderment and understanding.", author: "Unknown", category: "Science" },
  { text: "Science is humanity's ongoing dialogue with nature.", author: "Unknown", category: "Science" },
  { text: "Science is a candle that lights our path.", author: "Unknown", category: "Science" },
  { text: "Science, my lad, is made up of mistakes, but useful ones.", author: "Jules Verne", category: "Science" },
  { text: "Science is the great adventure of the mind.", author: "Unknown", category: "Science" }
];

export const financeQuotes: QuoteData[] = [
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett", category: "Finance" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett", category: "Finance" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett", category: "Finance" },
  { text: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", author: "Warren Buffett", category: "Finance" },
  { text: "The most important quality for an investor is temperament, not intellect.", author: "Warren Buffett", category: "Finance" },
  { text: "Diversification is protection against ignorance.", author: "Warren Buffett", category: "Finance" },
  { text: "Be fearful when others are greedy and greedy when others are fearful.", author: "Warren Buffett", category: "Finance" },
  { text: "Someone's sitting in the shade today because someone planted a tree long ago.", author: "Warren Buffett", category: "Finance" },
  { text: "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.", author: "Warren Buffett", category: "Finance" },
  { text: "Our favorite holding period is forever.", author: "Warren Buffett", category: "Finance" },
  { text: "Spend your money on the things money can buy. Spend your time on the things money can't.", author: "Haruki Murakami", category: "Finance" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", category: "Finance" },
  { text: "Beware of little expenses; a small leak will sink a great ship.", author: "Benjamin Franklin", category: "Finance" },
  { text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Jim Rohn", category: "Finance" },
  { text: "Compound interest is the eighth wonder of the world.", author: "Attributed to Albert Einstein", category: "Finance" },
  { text: "The four most dangerous words in investing are: 'This time it's different.'", author: "Sir John Templeton", category: "Finance" },
  { text: "Bull markets are born on pessimism, grown on skepticism, mature on optimism, and die on euphoria.", author: "Sir John Templeton", category: "Finance" },
  { text: "The investor's chief problem—and even his worst enemy—is likely to be himself.", author: "Benjamin Graham", category: "Finance" },
  { text: "In the short run, the market is a voting machine; in the long run, it is a weighing machine.", author: "Benjamin Graham", category: "Finance" },
  { text: "Price is what you pay. Value is what you truly receive.", author: "Benjamin Graham", category: "Finance" },
  { text: "The individual investor should act consistently as an investor and not as a speculator.", author: "Benjamin Graham", category: "Finance" },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch", category: "Finance" },
  { text: "Behind every stock is a company. Find out what it's doing.", author: "Peter Lynch", category: "Finance" },
  { text: "Far more money has been lost by investors trying to anticipate corrections than has been lost in corrections themselves.", author: "Peter Lynch", category: "Finance" },
  { text: "Invest in what you know.", author: "Peter Lynch", category: "Finance" },
  { text: "Only buy something that you'd be perfectly happy to hold if the market shut down for ten years.", author: "Warren Buffett", category: "Finance" },
  { text: "Money is a terrible master but an excellent servant.", author: "P. T. Barnum", category: "Finance" },
  { text: "Do not save what is left after spending; instead spend what is left after saving.", author: "Warren Buffett", category: "Finance" },
  { text: "It's not your salary that makes you rich, it's your spending habits.", author: "Charles A. Jaffe", category: "Finance" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", category: "Finance" },
  { text: "Too many people spend money they haven't earned to buy things they don't want to impress people they don't like.", author: "Will Rogers", category: "Finance" },
  { text: "Inflation is taxation without legislation.", author: "Milton Friedman", category: "Finance" },
  { text: "The only free lunch in investing is diversification.", author: "Harry Markowitz", category: "Finance" },
  { text: "If you don't find a way to make money while you sleep, you will work until you die.", author: "Warren Buffett", category: "Finance" },
  { text: "When the tide goes out, you discover who's been swimming naked.", author: "Warren Buffett", category: "Finance" },
  { text: "Cash combined with courage in a time of crisis is priceless.", author: "Warren Buffett", category: "Finance" },
  { text: "Forecasts may tell you a great deal about the forecaster; they tell you nothing about the future.", author: "Warren Buffett", category: "Finance" },
  { text: "It's not whether you're right or wrong that's important, but how much money you make when you're right and how much you lose when you're wrong.", author: "George Soros", category: "Finance" },
  { text: "Markets can remain irrational longer than you can remain solvent.", author: "John Maynard Keynes", category: "Finance" },
  { text: "The market is a pendulum that forever swings between unsustainable optimism (which makes stocks too expensive) and unjustified pessimism (which makes stocks too cheap).", author: "Jason Zweig", category: "Finance" },
  { text: "Good investing is boring.", author: "George Soros", category: "Finance" },
  { text: "Risk means more things can happen than will happen.", author: "Elroy Dimson", category: "Finance" },
  { text: "In investing, what is comfortable is rarely profitable.", author: "Robert Arnott", category: "Finance" },
  { text: "Money is like manure; it's not worth a thing unless it's spread around encouraging young things to grow.", author: "Thornton Wilder", category: "Finance" },
  { text: "When money realizes that it is in good hands, it wants to stay and multiply in those hands.", author: "Idowu Koyenikan", category: "Finance" },
  { text: "Patience is one of the most valuable attributes in investing.", author: "Charlie Munger", category: "Finance" },
  { text: "The big money is not in the buying or the selling, but in the waiting.", author: "Charlie Munger", category: "Finance" },
  { text: "Show me the incentive and I will show you the outcome.", author: "Charlie Munger", category: "Finance" },
  { text: "The first rule of compounding: Never interrupt it unnecessarily.", author: "Charlie Munger", category: "Finance" },
  { text: "Spend at least as much time researching a stock as you would choosing a refrigerator.", author: "Peter Lynch", category: "Finance" },
  { text: "Money often costs too much.", author: "Ralph Waldo Emerson", category: "Finance" },
  { text: "I will tell you how to become rich. Be fearful when others are greedy. Be greedy when others are fearful.", author: "Warren Buffett", category: "Finance" },
  { text: "A budget is telling your money where to go instead of wondering where it went.", author: "Dave Ramsey", category: "Finance" },
  { text: "Never depend on a single income. Make investment to create a second source.", author: "Warren Buffett", category: "Finance" },
  { text: "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.", author: "Dave Ramsey", category: "Finance" },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch", category: "Finance" },
  { text: "We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.", author: "Warren Buffett", category: "Finance" },
  { text: "Money is a tool. Used properly it makes something beautiful; used wrong, it makes a mess!", author: "Bradley Vincent", category: "Finance" },
  { text: "Financial freedom is available to those who learn about it and work for it.", author: "Robert Kiyosaki", category: "Finance" },
  { text: "The rich invest in time, the poor invest in money.", author: "Warren Buffett", category: "Finance" },
  { text: "The goal of the non-professional should not be to pick winners—neither he nor his 'helpers' can do that—but should rather be to own a cross-section of businesses that in aggregate are bound to do well.", author: "Warren Buffett", category: "Finance" },
  { text: "Wide diversification is only required when investors do not understand what they are doing.", author: "Warren Buffett", category: "Finance" },
  { text: "Money is always eager and ready to work for anyone who is ready to employ it.", author: "Idowu Koyenikan", category: "Finance" },
  { text: "The person who doesn't know where his next dollar is coming from usually doesn't know where his last dollar went.", author: "Unknown", category: "Finance" },
  { text: "Financial security and independence are like a three-legged stool resting on savings, insurance, and investments.", author: "Brian Tracy", category: "Finance" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn", category: "Finance" },
  { text: "Never test the depth of a river with both of your feet.", author: "Warren Buffett (paraphrasing an old proverb)", category: "Finance" },
  { text: "I never attempt to make money on the stock market. I buy on the assumption that they could close the market the next day and not reopen it for ten years.", author: "Warren Buffett", category: "Finance" },
  { text: "Saving is a great habit, but without investing and tracking, it just sleeps.", author: "Manoj Arora", category: "Finance" },
  { text: "Your wealth can be stolen, but the precious riches buried deep in your soul cannot.", author: "Minnie Riperton", category: "Finance" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison", category: "Finance" },
  { text: "Money, like emotions, is something you must control to keep your life on the right track.", author: "Natasha Munson", category: "Finance" },
  { text: "Never spend your money before you have earned it.", author: "Thomas Jefferson", category: "Finance" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau", category: "Finance" },
  { text: "Fortune favors the bold, but also favors the patient.", author: "Unknown", category: "Finance" },
  { text: "If you want to feel rich, just count the things you have that money can't buy.", author: "Unknown", category: "Finance" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill", category: "Finance" },
  { text: "It's not how much money you make, but how much money you keep.", author: "Robert Kiyosaki", category: "Finance" },
  { text: "A penny saved is a penny earned.", author: "Benjamin Franklin", category: "Finance" },
  { text: "Financial freedom is mental, emotional, and educational process.", author: "Robert Kiyosaki", category: "Finance" },
  { text: "Wealth is not his that has it, but his that enjoys it.", author: "Benjamin Franklin", category: "Finance" },
  { text: "Money is a great servant but a bad master.", author: "Francis Bacon", category: "Finance" },
  { text: "Wealth is the product of man's capacity to think.", author: "Ayn Rand", category: "Finance" },
  { text: "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", author: "Paul Samuelson", category: "Finance" },
  { text: "Not everything that can be counted counts, and not everything that counts can be counted.", author: "Albert Einstein", category: "Finance" },
  { text: "Financial fitness is not a pipe dream or a state of mind—it's a reality if you are willing to pursue it and embrace it.", author: "Will Robinson", category: "Finance" },
  { text: "Money grows on the tree of persistence.", author: "Japanese Proverb", category: "Finance" },
  { text: "What we really want to do is what we are really meant to do. When we do what we are meant to do, money comes to us.", author: "Julia Cameron", category: "Finance" },
  { text: "Prosperity is not without many fears and distastes; adversity not without many comforts and hopes.", author: "Francis Bacon", category: "Finance" },
  { text: "Wealth is like seawater; the more we drink, the thirstier we become.", author: "Arthur Schopenhauer", category: "Finance" },
  { text: "He who loses money, loses much; he who loses a friend, loses much more; he who loses faith, loses all.", author: "Eleanor Roosevelt", category: "Finance" },
  { text: "A wise person should have money in their head, but not in their heart.", author: "Jonathan Swift", category: "Finance" },
  { text: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand", category: "Finance" },
  { text: "You must gain control over your money or the lack of it will forever control you.", author: "Dave Ramsey", category: "Finance" },
  { text: "Wealth consists of caring less about what others think.", author: "Naval Ravikant", category: "Finance" },
  { text: "The real measure of your wealth is how much you'd be worth if you lost all your money.", author: "Unknown", category: "Finance" },
  { text: "To get rich, you have to be making money while you're asleep.", author: "David Bailey", category: "Finance" },
  { text: "Money is numbers and numbers never end. If it takes money to be happy, your search for happiness will never end.", author: "Bob Marley", category: "Finance" },
  { text: "Financial independence is about having more choices.", author: "Jean Chatzky", category: "Finance" },
  { text: "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought, and so broadens the mind.", author: "T. T. Munger", category: "Finance" }
];

// Export all quotes combined for easy access
export const allNewQuotes: QuoteData[] = [
  ...historyQuotes,
  ...scienceQuotes,
  ...financeQuotes
];